### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by zimbipw** [ervandew/keyring#4]
Any plans to migrate to Python 3?

**Comment by ervandew** [comment]
thanks for filing this issue. for some reason i thought i had already ported this to python3, but i definitely had not.

code has now been updated for python3 and i updated the docs with the new dependencies. everything seems to be working as expected, but please let me know if you run into any issues.

**Comment by zimbipw** [comment]
On Mon, May 18, 2020 at 01:15:18PM -0700, Eric Van Dewoestine wrote:
>thanks for filing this issue. for some reason i thought i had already ported
>this to python3, but i definitely had not.
>
>code has now been updated for python3 and i updated the docs with the new
>dependencies. everything seems to be working as expected, but please let me
>know if you run into any issues.

Thanks Eric.

Just another question, the keyring command is adding new credtiants to
the login keyring instead of the standard keyring, is this correct or am
I doing something stupid?
KR Frank

**Comment by ervandew** [comment]
Yes, using the 'login' keyring is by design, but you can supply `-k` or `--keyring` to change the keyring used. Can you try using that to see if it gives you access to the keyring you want to use?

**Comment by zimbipw** [comment]
On Tue, May 26, 2020 at 08:16:07AM -0700, Eric Van Dewoestine wrote:
>Yes, using the 'login' keyring is by design, but you can supply -k or --keyring
>to change the keyring used. Can you try using that to see if it gives you
>access to the keyring you want to use?

Yes this way I can add to the default keyring, yet have to find a way
for the userscript to read from the default keyring.

Thanks Frank

**Comment by ervandew** [comment]
if you are referring to the qutebrowser script, it just executes whatever `keyring` is on your path, so you could create a small wrapper script that supplies the `-k/--keyring` arg and put that into your path instead.

Ideally it would be nice if qutebrowser had support for custom settings that userscripts could use, but as far as I can see it doesn't support that. If you or anyone else finds out differently, please let me know.
